spring:
  cloud:
    aws:
      dynamodb:
        endpoint: ${AWS_ENDPOINT_URL:http://localstack:4566}
      region:
        static: us-east-2
      credentials:
        access-key: test
        secret-key: test

logging:
  level:
    com.amazonaws: DEBUG
    software.amazon.awssdk: DEBUG