spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
      dynamodb:
        endpoint: http://localhost:4566
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-2
blogger-service:
  queue: blogging-timeline-queue
server:
  port: 8085